# Generated by Django 3.1.1 on 2020-09-04 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_staff',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='locations.positions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='opened',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
