# Generated by Django 3.1.1 on 2020-09-10 21:34

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('locations', '0002_auto_20200904_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='opened',
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
